# Default values for qbittorrent.

image:
  repository: binhex/arch-qbittorrentvpn
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

env: {}
    # TZ: UTC
  # PUID: 1001
  # PGID: 1001
  # UMASK: 022

service:
  main:
    ports:
      main:
        port: 8080
  torrent:
    enabled: true
    type: ClusterIP
    ports:
      tcp:
        enabled: true
        port: 6881
        protocol: TCP
      udp:
        enabled: true
        port: 6881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: emptyDir


additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: /config/custom-cont-init.d
    name: qbittorrent-scripts
